# Generated by Django 3.1.2 on 2020-11-22 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_profile_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
