# Generated by Django 3.1.2 on 2020-11-22 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_auto_20201122_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='artilce_num',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
