# Generated by Django 3.1.2 on 2020-11-17 18:54

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20201117_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='thumb',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, quality=1, size=[1280, 720], upload_to=''),
        ),
    ]
