# Generated by Django 3.1.2 on 2020-11-04 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20201103_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Username',
        ),
    ]
