# Generated by Django 3.1.2 on 2020-11-22 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_profile_artilce_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='artilce_num',
            field=models.IntegerField(default=0),
        ),
    ]
